name: compute
description: Flutter's compute function made available for all non-Flutter Dart programs
version: 0.1.0
repository: https://github.com/dartsidedev/compute
homepage: https://github.com/vincevargadev
issue_tracker: https://github.com/dartsidedev/compute/issues
environment:
  sdk: '>=2.15.1 <3.0.0'

dependencies:
  meta: ^1.0.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
  platform: ^3.1.0
  file: ^6.1.2
